author: billofbong
database: false
description: "\r\n"
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: org.awesomecraft.plugins.edit.Edit
name: Edit
startup: postworld
url: http://awesomecraft.org/
version: '1.0'
commands:
  e:
    description: Edit a block.
    aliases: [edit]
  em:
    description: Change your EditMaterial
    aliases: [emat, editmat, editmaterial]
  be:
    description: Blocks placed change to your EditMaterial.
    aliases: [blockedit]
permissions:
  edit.be:
    default: op
  edit.edit:
    default: op
